// Generated by CoffeeScript 1.12.7
(function() {
  var Docs, apm, express, http, path;

  path = require('path');

  express = require('express');

  http = require('http');

  apm = require('../lib/apm-cli');

  Docs = require('../lib/docs');

  describe('apm docs', function() {
    var server;
    server = null;
    beforeEach(function() {
      var app, live;
      silenceOutput();
      spyOnToken();
      app = express();
      app.get('/wrap-guide', function(request, response) {
        return response.sendFile(path.join(__dirname, 'fixtures', 'wrap-guide.json'));
      });
      app.get('/install', function(request, response) {
        return response.sendFile(path.join(__dirname, 'fixtures', 'install.json'));
      });
      server = http.createServer(app);
      live = false;
      server.listen(3000, '127.0.0.1', function() {
        process.env.ATOM_PACKAGES_URL = "http://localhost:3000";
        return live = true;
      });
      return waitsFor(function() {
        return live;
      });
    });
    afterEach(function() {
      var done;
      done = false;
      server.close(function() {
        return done = true;
      });
      return waitsFor(function() {
        return done;
      });
    });
    it('logs an error if the package has no URL', function() {
      var callback;
      callback = jasmine.createSpy('callback');
      apm.run(['docs', 'install'], callback);
      waitsFor('waiting for command to complete', function() {
        return callback.callCount > 0;
      });
      return runs(function() {
        expect(console.error).toHaveBeenCalled();
        return expect(console.error.argsForCall[0][0].length).toBeGreaterThan(0);
      });
    });
    it("logs an error if the package name is missing or empty", function() {
      var callback;
      callback = jasmine.createSpy('callback');
      apm.run(['docs'], callback);
      waitsFor('waiting for command to complete', function() {
        return callback.callCount > 0;
      });
      return runs(function() {
        expect(console.error).toHaveBeenCalled();
        return expect(console.error.argsForCall[0][0].length).toBeGreaterThan(0);
      });
    });
    it("prints the package URL if called with the --print option (and does not open it)", function() {
      var callback;
      spyOn(Docs.prototype, 'openRepositoryUrl');
      callback = jasmine.createSpy('callback');
      apm.run(['docs', '--print', 'wrap-guide'], callback);
      waitsFor('waiting for command to complete', function() {
        return callback.callCount > 0;
      });
      return runs(function() {
        expect(Docs.prototype.openRepositoryUrl).not.toHaveBeenCalled();
        expect(console.log).toHaveBeenCalled();
        return expect(console.log.argsForCall[0][0]).toContain('https://github.com/atom/wrap-guide');
      });
    });
    it("prints the package URL if called with the -p short option (and does not open it)", function() {
      var callback;
      Docs = require('../lib/docs');
      spyOn(Docs.prototype, 'openRepositoryUrl');
      callback = jasmine.createSpy('callback');
      apm.run(['docs', '-p', 'wrap-guide'], callback);
      waitsFor('waiting for command to complete', function() {
        return callback.callCount > 0;
      });
      return runs(function() {
        expect(Docs.prototype.openRepositoryUrl).not.toHaveBeenCalled();
        expect(console.log).toHaveBeenCalled();
        return expect(console.log.argsForCall[0][0]).toContain('https://github.com/atom/wrap-guide');
      });
    });
    return it("opens the package URL", function() {
      var callback;
      spyOn(Docs.prototype, 'openRepositoryUrl');
      callback = jasmine.createSpy('callback');
      apm.run(['docs', 'wrap-guide'], callback);
      waitsFor('waiting for command to complete', function() {
        return callback.callCount > 0;
      });
      return runs(function() {
        return expect(Docs.prototype.openRepositoryUrl).toHaveBeenCalled();
      });
    });
  });

}).call(this);
