// Generated by CoffeeScript 1.12.7
(function() {
  var apm, express, http, path;

  path = require('path');

  express = require('express');

  http = require('http');

  apm = require('../lib/apm-cli');

  describe('apm featured', function() {
    var server;
    server = null;
    beforeEach(function() {
      var app, live;
      silenceOutput();
      spyOnToken();
      app = express();
      app.get('/packages/featured', function(request, response) {
        return response.sendFile(path.join(__dirname, 'fixtures', 'packages.json'));
      });
      app.get('/themes/featured', function(request, response) {
        return response.sendFile(path.join(__dirname, 'fixtures', 'themes.json'));
      });
      server = http.createServer(app);
      live = false;
      server.listen(3000, '127.0.0.1', function() {
        process.env.ATOM_API_URL = "http://localhost:3000";
        return live = true;
      });
      return waitsFor(function() {
        return live;
      });
    });
    afterEach(function() {
      var done;
      done = false;
      server.close(function() {
        return done = true;
      });
      return waitsFor(function() {
        return done;
      });
    });
    it('lists the featured packages and themes', function() {
      var callback;
      callback = jasmine.createSpy('callback');
      apm.run(['featured'], callback);
      waitsFor('waiting for command to complete', function() {
        return callback.callCount > 0;
      });
      return runs(function() {
        expect(console.log).toHaveBeenCalled();
        expect(console.log.argsForCall[1][0]).toContain('beverly-hills');
        expect(console.log.argsForCall[2][0]).toContain('multi-version');
        return expect(console.log.argsForCall[3][0]).toContain('duckblur');
      });
    });
    return describe('when the theme flag is specified', function() {
      return it("lists the featured themes", function() {
        var callback;
        callback = jasmine.createSpy('callback');
        apm.run(['featured', '--themes'], callback);
        waitsFor('waiting for command to complete', function() {
          return callback.callCount > 0;
        });
        return runs(function() {
          expect(console.log).toHaveBeenCalled();
          expect(console.log.argsForCall[1][0]).toContain('duckblur');
          return expect(console.log.argsForCall[2][0]).toBeUndefined();
        });
      });
    });
  });

}).call(this);
