// Generated by CoffeeScript 1.12.7
(function() {
  var Packages;

  Packages = require('../lib/packages');

  describe('getRemote', function() {
    it('returns origin if remote could not be determined', function() {
      return expect(Packages.getRemote()).toEqual('origin');
    });
    it('returns repository.url', function() {
      var pack;
      pack = {
        repository: {
          type: 'git',
          url: 'https://github.com/atom/apm.git'
        }
      };
      return expect(Packages.getRemote(pack)).toEqual(pack.repository.url);
    });
    return it('returns repository', function() {
      var pack;
      pack = {
        repository: 'https://github.com/atom/apm'
      };
      return expect(Packages.getRemote(pack)).toEqual(pack.repository);
    });
  });

}).call(this);
