// Generated by CoffeeScript 1.12.7
(function() {
  var auth;

  auth = require('../lib/auth');

  global.silenceOutput = function(callThrough) {
    var i, len, ref, results, spy;
    if (callThrough == null) {
      callThrough = false;
    }
    spyOn(console, 'log');
    spyOn(console, 'error');
    spyOn(process.stdout, 'write');
    spyOn(process.stderr, 'write');
    if (callThrough) {
      ref = [console.log, console.error, process.stdout.write, process.stderr.write];
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        spy = ref[i];
        results.push(spy.andCallThrough());
      }
      return results;
    }
  };

  global.spyOnToken = function() {
    return spyOn(auth, 'getToken').andCallFake(function(callback) {
      return callback(null, 'token');
    });
  };

}).call(this);
