// Generated by CoffeeScript 1.12.7
(function() {
  var apm, express, http, path;

  path = require('path');

  express = require('express');

  http = require('http');

  apm = require('../lib/apm-cli');

  describe('apm view', function() {
    var server;
    server = null;
    beforeEach(function() {
      var app, live;
      silenceOutput();
      spyOnToken();
      app = express();
      app.get('/wrap-guide', function(request, response) {
        return response.sendFile(path.join(__dirname, 'fixtures', 'wrap-guide.json'));
      });
      server = http.createServer(app);
      live = false;
      server.listen(3000, '127.0.0.1', function() {
        process.env.ATOM_PACKAGES_URL = "http://localhost:3000";
        return live = true;
      });
      return waitsFor(function() {
        return live;
      });
    });
    afterEach(function() {
      var done;
      done = false;
      server.close(function() {
        return done = true;
      });
      return waitsFor(function() {
        return done;
      });
    });
    it('displays information about the package', function() {
      var callback;
      callback = jasmine.createSpy('callback');
      apm.run(['view', 'wrap-guide'], callback);
      waitsFor('waiting for view to complete', function() {
        return callback.callCount > 0;
      });
      return runs(function() {
        expect(console.log).toHaveBeenCalled();
        expect(console.log.argsForCall[0][0]).toContain('wrap-guide');
        expect(console.log.argsForCall[1][0]).toContain('0.14.0');
        expect(console.log.argsForCall[2][0]).toContain('https://github.com/atom/wrap-guide');
        return expect(console.log.argsForCall[3][0]).toContain('new version');
      });
    });
    it("logs an error if the package name is missing or empty", function() {
      var callback;
      callback = jasmine.createSpy('callback');
      apm.run(['view'], callback);
      waitsFor('waiting for view to complete', function() {
        return callback.callCount > 0;
      });
      return runs(function() {
        expect(console.error).toHaveBeenCalled();
        return expect(console.error.argsForCall[0][0].length).toBeGreaterThan(0);
      });
    });
    return describe("when a compatible Atom version is specified", function() {
      return it("displays the latest compatible version of the package", function() {
        var callback;
        callback = jasmine.createSpy('callback');
        apm.run(['view', 'wrap-guide', '--compatible', '1.5.0'], callback);
        waitsFor('waiting for view to complete', 600000, function() {
          return callback.callCount === 1;
        });
        return runs(function() {
          expect(console.log.argsForCall[0][0]).toContain('wrap-guide');
          expect(console.log.argsForCall[1][0]).toContain('0.3.0');
          expect(console.log.argsForCall[2][0]).toContain('https://github.com/atom2/wrap-guide');
          return expect(console.log.argsForCall[3][0]).toContain('old version');
        });
      });
    });
  });

}).call(this);
